id: IEA38ACA1
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T03:45:55+00:00'
last_modified: '2022-06-07T17:31:28.530673+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG5615
  title: སྲོང་བཙན་ལོ་རྒྱུས་ཞིབ་འཇུག་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    E12E:
      image_group_id: I1KG5645
      title: ''
      total_pages: 616
      order: 1
      base_file: E12E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
