id: P003095
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG5615
  title: སྲོང་བཙན་ལོ་རྒྱུས་ཞིབ་འཇུག་
  author: ''
  volumes:
    9f4eb140f3bc49d19d62789389504842:
      image_group_id: I1KG5645
      title: ''
      volume_number: 1
      total_pages: 616
      base_file: v001.txt
